### ISSUE TITLE
Error: Can't walk dependency graph: Cannot find module 'postcss-loader'

### ISSUE THREAD

**Issue by walsh-rose** [zhentian-wan/angular-md-table#12]
Thank you so much for offering this library!

I have imported `"angular-md-table": "^1.4.0"` into my project via package.json.

When I try running my project's `createBrowserifyBundle()` function (shown below), which is how I build my code (importing libraries via ES6 imports), I get this error:

```
Error: Can't walk dependency graph: Cannot find module 'postcss-loader' from '/mnt/c/code/my_project/node_modules/angular-md-table/webpack.config.js'
    required by /mnt/c/code/my_project/node_modules/angular-md-table/webpack.config.js
    at /mnt/c/code/my_project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:115:35
    at processDirs (/mnt/c/code/my_project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:268:39)
    at isdir (/mnt/c/code/my_project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:275:32)
    at /mnt/c/code/my_project/node_modules/browser-resolve/node_modules/resolve/lib/async.js:25:69
    at FSReqCallback.oncomplete (fs.js:167:21)
```
Thank you for any help.

```
function createBrowserifyBundle() {
  const bundleStream = browserify(jsEntry)
    .transform(babelify, { presets: ['es2015'] })
    .transform(ngAnnotate)
    .bundle() 
  return (
    bundleStream
      .pipe(source(jsDevCustomPiece))
      .pipe(dest(staticPathJs))
  )
}
```

P.S. I realize that https://github.com/michael-ciniawsky/postcss-load-config/issues/196 is also a problem, but the real root cause is here in `zhentian-wan/angular-md-table`.

**Comment by zhentian-wan** [comment]
Hi, thanks for using this library.

Looks like you are using gulp? ... I suggest you use umd version

```
angular-md-table/dist/angular-md-table.umd.min.js
```
you can include those script into header.... 

don't use the following..  those are for webpack bundler, if you are not using webpack
```
require('angular-md-table/dist/angular-md-table.min.js');
```

You can also check out https://github.com/swimlane/angular-data-table repo...
